name: Python ruff lint

on:
  pull_request:
    branches:
      - dev

concurrency:
  group: python-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ruff:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
