name: Shell shellcheck lint and format

on:
  pull_request:
    branches:
      - dev
  pull_request_target:
    branches:
      - dev

concurrency:
  group: shell-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
